In [1]:
# Interactive plotting
%matplotlib widget

In [2]:
import numpy as np
import matplotlib.pyplot as plt

plt.close("all")

In [6]:
A = np.array([[1, 0], [0, 1]])
x = np.array([1, 0])
print(A)
print(x)

[[1 0]
 [0 1]]
[1 0]


In [7]:
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html#numpy.random.rand
np.random.rand(2, 2)

array([[0.26871236, 0.16394328],
       [0.33578585, 0.46547541]])

In [10]:
test_det = np.array([[1, 2], [3, 4]])
np.linalg.det(test_det)

np.float64(-2.0000000000000004)

In [8]:
test_sum = np.array([[1, 2], [3, 4]])
np.sum(test_sum)

np.int64(10)

In [5]:
test_prod = np.array([[1, 2], [3, 4]])
np.prod(test_prod)

np.int64(24)

In [7]:
test_diag = np.array([[1, 2], [3, 4]])
np.diag(test_diag)

array([1, 4])

In [10]:
test_symmetric = np.random.rand(2, 2)
print("previous:", test_symmetric)
test_symmetric[0][1] = test_symmetric[1][0]
print("current:", test_symmetric)

previous: [[0.83598292 0.65158962]
 [0.38677373 0.76489224]]
current: [[0.83598292 0.38677373]
 [0.38677373 0.76489224]]


In [16]:
A = np.array([[13, -4, -2], [-4, 13, 2], [-2, 2, 10]])
np.linalg.eig(A)

EigResult(eigenvalues=array([ 9., 18.,  9.]), eigenvectors=array([[-0.74535599, -0.66666667, -0.00865363],
       [-0.59628479,  0.66666667, -0.45410636],
       [-0.2981424 ,  0.33333333,  0.89090546]]))